import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink, RouterLinkActive } from '@angular/router';

interface Flight {
  id: number;
  flightNumber: string;
  airline: string;
  from: string;
  to: string;
  departureDate: string;
  returnDate: string;
  departureTime: string;
  arrivalTime: string;
  duration: string;
  travelClass: string;
  price: number;
  stops: number;
}

@Component({
  selector: 'app-flight-list',
   imports: [CommonModule,FormsModule,RouterLink,RouterLinkActive],
  templateUrl: './flight.component.html'
})
export class FlightComponent implements OnInit {
   flights: Flight[] = [];  // All flight data
  filteredFlights: Flight[] = []; // Filtered flight data based on the search
  currentPage = 1;
  flightsPerPage = 10;

  filters = {
    stops: new Set<number>(),
    airlines: new Set<string>(),
    maxPrice: 10000
  };

  constructor() {}

  ngOnInit(): void {
    // Define mock flight data in JSON format
    this.flights = this.getMockFlights();
    this.applyFilters();
  }

  // Function to generate mock flight data
  getMockFlights(...args: []): Flight[] {
    return [
 {
    "id": 1,
    "flightNumber": "AI321",
    "airline": "AirAsia",
    "from": "Chennai",
    "to": "Delhi",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "07:19",
    "arrivalTime": "11:49",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 5988,
    "stops": 1
  },
  {
    "id": 2,
    "flightNumber": "AI609",
    "airline": "Air India",
    "from": "Hyderabad",
    "to": "Delhi",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "15:03",
    "arrivalTime": "19:18",
    "duration": "4h 15m",
    "travelClass": "Economy",
    "price": 6407,
    "stops": 1
  },
  {
    "id": 3,
    "flightNumber": "AI161",
    "airline": "Air India",
    "from": "Bangalore",
    "to": "Chennai",
    "departureDate": "2025-05-29",
    "returnDate": "",
    "departureTime": "18:34",
    "arrivalTime": "23:34",
    "duration": "5h",
    "travelClass": "Economy",
    "price": 9634,
    "stops": 0
  },
  {
    "id": 4,
    "flightNumber": "AI763",
    "airline": "AirAsia",
    "from": "Chennai",
    "to": "Mumbai",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "23:30",
    "arrivalTime": "00:45",
    "duration": "1h 15m",
    "travelClass": "Economy",
    "price": 5068,
    "stops": 0
  },
  {
    "id": 5,
    "flightNumber": "SP892",
    "airline": "SpiceJet",
    "from": "Kolkata",
    "to": "Pune",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "00:10",
    "arrivalTime": "04:40",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 4853,
    "stops": 0
  },
  {
    "id": 6,
    "flightNumber": "VI313",
    "airline": "Vistara",
    "from": "Pune",
    "to": "Mumbai",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "11:19",
    "arrivalTime": "17:04",
    "duration": "5h 45m",
    "travelClass": "Economy",
    "price": 7519,
    "stops": 0
  },
  {
    "id": 7,
    "flightNumber": "GO251",
    "airline": "Go First",
    "from": "Mumbai",
    "to": "Ahmedabad",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "08:19",
    "arrivalTime": "13:34",
    "duration": "5h 15m",
    "travelClass": "Economy",
    "price": 3937,
    "stops": 1
  },
  {
    "id": 8,
    "flightNumber": "IN373",
    "airline": "IndiGo",
    "from": "Mumbai",
    "to": "Hyderabad",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "23:26",
    "arrivalTime": "04:11",
    "duration": "4h 45m",
    "travelClass": "Economy",
    "price": 9587,
    "stops": 0
  },
  {
    "id": 9,
    "flightNumber": "AI252",
    "airline": "AirAsia",
    "from": "Ahmedabad",
    "to": "Mumbai",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "10:22",
    "arrivalTime": "14:52",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 6850,
    "stops": 0
  },
  {
    "id": 10,
    "flightNumber": "VI512",
    "airline": "Vistara",
    "from": "Hyderabad",
    "to": "Kolkata",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "02:39",
    "arrivalTime": "08:09",
    "duration": "5h 30m",
    "travelClass": "Economy",
    "price": 9900,
    "stops": 1
  },
  {
    "id": 11,
    "flightNumber": "GO588",
    "airline": "Go First",
    "from": "Pune",
    "to": "Delhi",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "11:17",
    "arrivalTime": "15:17",
    "duration": "4h",
    "travelClass": "Economy",
    "price": 6944,
    "stops": 1
  },
  {
    "id": 12,
    "flightNumber": "AI656",
    "airline": "Air India",
    "from": "Ahmedabad",
    "to": "Chennai",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "12:19",
    "arrivalTime": "16:19",
    "duration": "4h",
    "travelClass": "Economy",
    "price": 4196,
    "stops": 0
  },
  {
    "id": 13,
    "flightNumber": "SP732",
    "airline": "SpiceJet",
    "from": "Bangalore",
    "to": "Mumbai",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "03:25",
    "arrivalTime": "04:25",
    "duration": "1h",
    "travelClass": "Economy",
    "price": 9304,
    "stops": 1
  },
  {
    "id": 14,
    "flightNumber": "IN427",
    "airline": "IndiGo",
    "from": "Kolkata",
    "to": "Hyderabad",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "07:53",
    "arrivalTime": "09:53",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 4374,
    "stops": 0
  },
  {
    "id": 15,
    "flightNumber": "VI501",
    "airline": "Vistara",
    "from": "Kolkata",
    "to": "Ahmedabad",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "12:19",
    "arrivalTime": "14:19",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 8348,
    "stops": 0
  },
  {
    "id": 16,
    "flightNumber": "AI127",
    "airline": "AirAsia",
    "from": "Kolkata",
    "to": "Delhi",
    "departureDate": "2025-05-29",
    "returnDate": "",
    "departureTime": "17:31",
    "arrivalTime": "22:31",
    "duration": "5h",
    "travelClass": "Economy",
    "price": 5912,
    "stops": 0
  },
  {
    "id": 17,
    "flightNumber": "AI604",
    "airline": "Air India",
    "from": "Pune",
    "to": "Ahmedabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "19:31",
    "arrivalTime": "20:31",
    "duration": "1h",
    "travelClass": "Economy",
    "price": 8758,
    "stops": 1
  },
  {
    "id": 18,
    "flightNumber": "VI172",
    "airline": "Vistara",
    "from": "Chennai",
    "to": "Mumbai",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "09:33",
    "arrivalTime": "10:48",
    "duration": "1h 15m",
    "travelClass": "Economy",
    "price": 9369,
    "stops": 0
  },
  {
    "id": 19,
    "flightNumber": "VI245",
    "airline": "Vistara",
    "from": "Pune",
    "to": "Ahmedabad",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "11:07",
    "arrivalTime": "13:07",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 6631,
    "stops": 0
  },
  {
    "id": 20,
    "flightNumber": "GO841",
    "airline": "Go First",
    "from": "Chennai",
    "to": "Ahmedabad",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "07:53",
    "arrivalTime": "09:23",
    "duration": "1h 30m",
    "travelClass": "Economy",
    "price": 5120,
    "stops": 1
  },
  {
    "id": 21,
    "flightNumber": "IN426",
    "airline": "IndiGo",
    "from": "Mumbai",
    "to": "Hyderabad",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "23:52",
    "arrivalTime": "01:52",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 4671,
    "stops": 0
  },
  {
    "id": 22,
    "flightNumber": "AI513",
    "airline": "AirAsia",
    "from": "Bangalore",
    "to": "Kolkata",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "14:34",
    "arrivalTime": "18:34",
    "duration": "4h",
    "travelClass": "Economy",
    "price": 5926,
    "stops": 1
  },
  {
    "id": 23,
    "flightNumber": "AI872",
    "airline": "Air India",
    "from": "Ahmedabad",
    "to": "Mumbai",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "14:49",
    "arrivalTime": "19:49",
    "duration": "5h",
    "travelClass": "Economy",
    "price": 4399,
    "stops": 1
  },
  {
    "id": 24,
    "flightNumber": "VI231",
    "airline": "Vistara",
    "from": "Ahmedabad",
    "to": "Delhi",
    "departureDate": "2025-05-26",
    "returnDate": "",
    "departureTime": "03:58",
    "arrivalTime": "07:58",
    "duration": "4h",
    "travelClass": "Economy",
    "price": 7390,
    "stops": 0
  },
  {
    "id": 25,
    "flightNumber": "VI372",
    "airline": "Vistara",
    "from": "Ahmedabad",
    "to": "Kolkata",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "14:48",
    "arrivalTime": "19:18",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 7642,
    "stops": 1
  },
  {
    "id": 26,
    "flightNumber": "SP458",
    "airline": "SpiceJet",
    "from": "Ahmedabad",
    "to": "Hyderabad",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "22:43",
    "arrivalTime": "03:28",
    "duration": "4h 45m",
    "travelClass": "Economy",
    "price": 8927,
    "stops": 1
  },
  {
    "id": 27,
    "flightNumber": "AI430",
    "airline": "Air India",
    "from": "Pune",
    "to": "Hyderabad",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "05:50",
    "arrivalTime": "09:05",
    "duration": "3h 15m",
    "travelClass": "Economy",
    "price": 3745,
    "stops": 1
  },
  {
    "id": 28,
    "flightNumber": "VI177",
    "airline": "Vistara",
    "from": "Delhi",
    "to": "Bangalore",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "22:58",
    "arrivalTime": "03:13",
    "duration": "4h 15m",
    "travelClass": "Economy",
    "price": 3550,
    "stops": 0
  },
  {
    "id": 29,
    "flightNumber": "VI663",
    "airline": "Vistara",
    "from": "Chennai",
    "to": "Ahmedabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "01:58",
    "arrivalTime": "05:43",
    "duration": "3h 45m",
    "travelClass": "Economy",
    "price": 7192,
    "stops": 0
  },
  {
    "id": 30,
    "flightNumber": "SP234",
    "airline": "SpiceJet",
    "from": "Ahmedabad",
    "to": "Bangalore",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "19:38",
    "arrivalTime": "00:23",
    "duration": "4h 45m",
    "travelClass": "Economy",
    "price": 6089,
    "stops": 0
  },
  {
    "id": 31,
    "flightNumber": "AI271",
    "airline": "AirAsia",
    "from": "Kolkata",
    "to": "Ahmedabad",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "23:40",
    "arrivalTime": "05:10",
    "duration": "5h 30m",
    "travelClass": "Economy",
    "price": 5440,
    "stops": 0
  },
  {
    "id": 32,
    "flightNumber": "AI616",
    "airline": "AirAsia",
    "from": "Chennai",
    "to": "Kolkata",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "21:30",
    "arrivalTime": "22:30",
    "duration": "1h",
    "travelClass": "Economy",
    "price": 5042,
    "stops": 1
  },
  {
    "id": 33,
    "flightNumber": "AI641",
    "airline": "AirAsia",
    "from": "Kolkata",
    "to": "Chennai",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "14:46",
    "arrivalTime": "17:46",
    "duration": "3h",
    "travelClass": "Economy",
    "price": 7263,
    "stops": 1
  },
  {
    "id": 34,
    "flightNumber": "AI200",
    "airline": "Air India",
    "from": "Mumbai",
    "to": "Hyderabad",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "19:45",
    "arrivalTime": "00:45",
    "duration": "5h",
    "travelClass": "Economy",
    "price": 7292,
    "stops": 1
  },
  {
    "id": 35,
    "flightNumber": "VI761",
    "airline": "Vistara",
    "from": "Ahmedabad",
    "to": "Pune",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "12:42",
    "arrivalTime": "17:12",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 7139,
    "stops": 1
  },
  {
    "id": 36,
    "flightNumber": "AI627",
    "airline": "AirAsia",
    "from": "Hyderabad",
    "to": "Pune",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "01:15",
    "arrivalTime": "03:45",
    "duration": "2h 30m",
    "travelClass": "Economy",
    "price": 3886,
    "stops": 0
  },
  {
    "id": 37,
    "flightNumber": "VI495",
    "airline": "Vistara",
    "from": "Chennai",
    "to": "Pune",
    "departureDate": "2025-05-29",
    "returnDate": "",
    "departureTime": "07:59",
    "arrivalTime": "09:29",
    "duration": "1h 30m",
    "travelClass": "Economy",
    "price": 8613,
    "stops": 1
  },
  {
    "id": 38,
    "flightNumber": "SP374",
    "airline": "SpiceJet",
    "from": "Kolkata",
    "to": "Chennai",
    "departureDate": "2025-05-29",
    "returnDate": "",
    "departureTime": "16:46",
    "arrivalTime": "18:16",
    "duration": "1h 30m",
    "travelClass": "Economy",
    "price": 9579,
    "stops": 0
  },
  {
    "id": 39,
    "flightNumber": "VI619",
    "airline": "Vistara",
    "from": "Hyderabad",
    "to": "Delhi",
    "departureDate": "2025-05-26",
    "returnDate": "",
    "departureTime": "23:25",
    "arrivalTime": "02:10",
    "duration": "2h 45m",
    "travelClass": "Economy",
    "price": 7864,
    "stops": 0
  },
  {
    "id": 40,
    "flightNumber": "SP996",
    "airline": "SpiceJet",
    "from": "Delhi",
    "to": "Hyderabad",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "04:12",
    "arrivalTime": "09:42",
    "duration": "5h 30m",
    "travelClass": "Economy",
    "price": 8848,
    "stops": 0
  },
  {
    "id": 41,
    "flightNumber": "GO665",
    "airline": "Go First",
    "from": "Kolkata",
    "to": "Chennai",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "02:23",
    "arrivalTime": "04:38",
    "duration": "2h 15m",
    "travelClass": "Economy",
    "price": 5456,
    "stops": 0
  },
  {
    "id": 42,
    "flightNumber": "AI625",
    "airline": "AirAsia",
    "from": "Hyderabad",
    "to": "Kolkata",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "16:13",
    "arrivalTime": "19:28",
    "duration": "3h 15m",
    "travelClass": "Economy",
    "price": 5189,
    "stops": 0
  },
  {
    "id": 43,
    "flightNumber": "AI137",
    "airline": "AirAsia",
    "from": "Pune",
    "to": "Hyderabad",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "00:15",
    "arrivalTime": "03:30",
    "duration": "3h 15m",
    "travelClass": "Economy",
    "price": 3012,
    "stops": 0
  },
  {
    "id": 44,
    "flightNumber": "AI232",
    "airline": "Air India",
    "from": "Chennai",
    "to": "Bangalore",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "20:41",
    "arrivalTime": "22:41",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 3846,
    "stops": 0
  },
  {
    "id": 45,
    "flightNumber": "AI907",
    "airline": "Air India",
    "from": "Mumbai",
    "to": "Chennai",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "19:12",
    "arrivalTime": "23:57",
    "duration": "4h 45m",
    "travelClass": "Economy",
    "price": 8915,
    "stops": 0
  },
  {
    "id": 46,
    "flightNumber": "AI434",
    "airline": "AirAsia",
    "from": "Pune",
    "to": "Mumbai",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "13:49",
    "arrivalTime": "15:34",
    "duration": "1h 45m",
    "travelClass": "Economy",
    "price": 7185,
    "stops": 0
  },
  {
    "id": 47,
    "flightNumber": "SP745",
    "airline": "SpiceJet",
    "from": "Bangalore",
    "to": "Kolkata",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "14:30",
    "arrivalTime": "17:30",
    "duration": "3h",
    "travelClass": "Economy",
    "price": 9310,
    "stops": 1
  },
  {
    "id": 48,
    "flightNumber": "VI216",
    "airline": "Vistara",
    "from": "Pune",
    "to": "Chennai",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "07:05",
    "arrivalTime": "10:50",
    "duration": "3h 45m",
    "travelClass": "Economy",
    "price": 5484,
    "stops": 1
  },
  {
    "id": 49,
    "flightNumber": "SP497",
    "airline": "SpiceJet",
    "from": "Delhi",
    "to": "Bangalore",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "21:50",
    "arrivalTime": "03:20",
    "duration": "5h 30m",
    "travelClass": "Economy",
    "price": 6225,
    "stops": 1
  },
  {
    "id": 50,
    "flightNumber": "AI444",
    "airline": "AirAsia",
    "from": "Ahmedabad",
    "to": "Hyderabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "21:40",
    "arrivalTime": "02:55",
    "duration": "5h 15m",
    "travelClass": "Economy",
    "price": 6984,
    "stops": 0
  },
  {
    "id": 51,
    "flightNumber": "SP874",
    "airline": "SpiceJet",
    "from": "Pune",
    "to": "Bangalore",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "15:25",
    "arrivalTime": "18:10",
    "duration": "2h 45m",
    "travelClass": "Economy",
    "price": 9214,
    "stops": 1
  },
  {
    "id": 52,
    "flightNumber": "AI593",
    "airline": "Air India",
    "from": "Ahmedabad",
    "to": "Delhi",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "07:49",
    "arrivalTime": "12:34",
    "duration": "4h 45m",
    "travelClass": "Economy",
    "price": 7499,
    "stops": 0
  },
  {
    "id": 53,
    "flightNumber": "IN701",
    "airline": "IndiGo",
    "from": "Bangalore",
    "to": "Hyderabad",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "16:31",
    "arrivalTime": "19:01",
    "duration": "2h 30m",
    "travelClass": "Economy",
    "price": 9282,
    "stops": 1
  },
  {
    "id": 54,
    "flightNumber": "AI718",
    "airline": "AirAsia",
    "from": "Hyderabad",
    "to": "Ahmedabad",
    "departureDate": "2025-05-29",
    "returnDate": "",
    "departureTime": "04:01",
    "arrivalTime": "05:01",
    "duration": "1h",
    "travelClass": "Economy",
    "price": 9409,
    "stops": 0
  },
  {
    "id": 55,
    "flightNumber": "IN395",
    "airline": "IndiGo",
    "from": "Bangalore",
    "to": "Chennai",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "04:55",
    "arrivalTime": "07:10",
    "duration": "2h 15m",
    "travelClass": "Economy",
    "price": 6803,
    "stops": 0
  },
  {
    "id": 56,
    "flightNumber": "AI550",
    "airline": "AirAsia",
    "from": "Ahmedabad",
    "to": "Bangalore",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "03:05",
    "arrivalTime": "07:35",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 6653,
    "stops": 0
  },
  {
    "id": 57,
    "flightNumber": "IN589",
    "airline": "IndiGo",
    "from": "Ahmedabad",
    "to": "Kolkata",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "19:31",
    "arrivalTime": "21:01",
    "duration": "1h 30m",
    "travelClass": "Economy",
    "price": 7180,
    "stops": 0
  },
  {
    "id": 58,
    "flightNumber": "IN762",
    "airline": "IndiGo",
    "from": "Hyderabad",
    "to": "Delhi",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "18:13",
    "arrivalTime": "20:28",
    "duration": "2h 15m",
    "travelClass": "Economy",
    "price": 9137,
    "stops": 1
  },
  {
    "id": 59,
    "flightNumber": "GO553",
    "airline": "Go First",
    "from": "Mumbai",
    "to": "Delhi",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "02:08",
    "arrivalTime": "07:08",
    "duration": "5h",
    "travelClass": "Economy",
    "price": 4953,
    "stops": 1
  },
  {
    "id": 60,
    "flightNumber": "SP934",
    "airline": "SpiceJet",
    "from": "Mumbai",
    "to": "Hyderabad",
    "departureDate": "2025-05-26",
    "returnDate": "",
    "departureTime": "13:21",
    "arrivalTime": "19:06",
    "duration": "5h 45m",
    "travelClass": "Economy",
    "price": 4100,
    "stops": 0
  },
  {
    "id": 61,
    "flightNumber": "AI926",
    "airline": "Air India",
    "from": "Ahmedabad",
    "to": "Hyderabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "22:45",
    "arrivalTime": "01:30",
    "duration": "2h 45m",
    "travelClass": "Economy",
    "price": 8489,
    "stops": 1
  },
  {
    "id": 62,
    "flightNumber": "GO978",
    "airline": "Go First",
    "from": "Kolkata",
    "to": "Ahmedabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "11:23",
    "arrivalTime": "14:08",
    "duration": "2h 45m",
    "travelClass": "Economy",
    "price": 8665,
    "stops": 0
  },
  {
    "id": 63,
    "flightNumber": "VI996",
    "airline": "Vistara",
    "from": "Pune",
    "to": "Mumbai",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "20:33",
    "arrivalTime": "22:18",
    "duration": "1h 45m",
    "travelClass": "Economy",
    "price": 9380,
    "stops": 0
  },
  {
    "id": 64,
    "flightNumber": "GO199",
    "airline": "Go First",
    "from": "Bangalore",
    "to": "Ahmedabad",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "17:20",
    "arrivalTime": "18:50",
    "duration": "1h 30m",
    "travelClass": "Economy",
    "price": 6645,
    "stops": 1
  },
  {
    "id": 65,
    "flightNumber": "GO522",
    "airline": "Go First",
    "from": "Pune",
    "to": "Ahmedabad",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "10:40",
    "arrivalTime": "12:40",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 4328,
    "stops": 0
  },
  {
    "id": 66,
    "flightNumber": "SP727",
    "airline": "SpiceJet",
    "from": "Delhi",
    "to": "Bangalore",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "07:53",
    "arrivalTime": "12:08",
    "duration": "4h 15m",
    "travelClass": "Economy",
    "price": 9426,
    "stops": 0
  },
  {
    "id": 67,
    "flightNumber": "SP379",
    "airline": "SpiceJet",
    "from": "Mumbai",
    "to": "Pune",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "07:00",
    "arrivalTime": "08:15",
    "duration": "1h 15m",
    "travelClass": "Economy",
    "price": 6159,
    "stops": 0
  },
  {
    "id": 68,
    "flightNumber": "SP695",
    "airline": "SpiceJet",
    "from": "Pune",
    "to": "Ahmedabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "18:29",
    "arrivalTime": "21:59",
    "duration": "3h 30m",
    "travelClass": "Economy",
    "price": 5319,
    "stops": 1
  },
  {
    "id": 69,
    "flightNumber": "IN353",
    "airline": "IndiGo",
    "from": "Mumbai",
    "to": "Chennai",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "21:09",
    "arrivalTime": "23:09",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 7514,
    "stops": 0
  },
  {
    "id": 70,
    "flightNumber": "GO301",
    "airline": "Go First",
    "from": "Hyderabad",
    "to": "Delhi",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "20:08",
    "arrivalTime": "21:08",
    "duration": "1h",
    "travelClass": "Economy",
    "price": 6317,
    "stops": 1
  },
  {
    "id": 71,
    "flightNumber": "IN503",
    "airline": "IndiGo",
    "from": "Ahmedabad",
    "to": "Hyderabad",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "10:41",
    "arrivalTime": "13:41",
    "duration": "3h",
    "travelClass": "Economy",
    "price": 4359,
    "stops": 0
  },
  {
    "id": 72,
    "flightNumber": "AI457",
    "airline": "Air India",
    "from": "Mumbai",
    "to": "Delhi",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "13:04",
    "arrivalTime": "18:34",
    "duration": "5h 30m",
    "travelClass": "Economy",
    "price": 3379,
    "stops": 1
  },
  {
    "id": 73,
    "flightNumber": "AI484",
    "airline": "AirAsia",
    "from": "Bangalore",
    "to": "Chennai",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "03:28",
    "arrivalTime": "05:28",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 7798,
    "stops": 0
  },
  {
    "id": 74,
    "flightNumber": "IN436",
    "airline": "IndiGo",
    "from": "Delhi",
    "to": "Chennai",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "08:28",
    "arrivalTime": "14:13",
    "duration": "5h 45m",
    "travelClass": "Economy",
    "price": 4983,
    "stops": 0
  },
  {
    "id": 75,
    "flightNumber": "AI609",
    "airline": "Air India",
    "from": "Kolkata",
    "to": "Bangalore",
    "departureDate": "2025-05-25",
    "returnDate": "",
    "departureTime": "21:36",
    "arrivalTime": "00:36",
    "duration": "3h",
    "travelClass": "Economy",
    "price": 3142,
    "stops": 1
  },
  {
    "id": 76,
    "flightNumber": "VI891",
    "airline": "Vistara",
    "from": "Bangalore",
    "to": "Chennai",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "19:47",
    "arrivalTime": "00:32",
    "duration": "4h 45m",
    "travelClass": "Economy",
    "price": 3704,
    "stops": 0
  },
  {
    "id": 77,
    "flightNumber": "SP420",
    "airline": "SpiceJet",
    "from": "Kolkata",
    "to": "Pune",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "20:34",
    "arrivalTime": "01:34",
    "duration": "5h",
    "travelClass": "Economy",
    "price": 3895,
    "stops": 1
  },
  {
    "id": 78,
    "flightNumber": "SP166",
    "airline": "SpiceJet",
    "from": "Bangalore",
    "to": "Hyderabad",
    "departureDate": "2025-05-24",
    "returnDate": "",
    "departureTime": "14:37",
    "arrivalTime": "18:07",
    "duration": "3h 30m",
    "travelClass": "Economy",
    "price": 9943,
    "stops": 0
  },
  {
    "id": 79,
    "flightNumber": "AI467",
    "airline": "Air India",
    "from": "Pune",
    "to": "Delhi",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "16:44",
    "arrivalTime": "18:59",
    "duration": "2h 15m",
    "travelClass": "Economy",
    "price": 7013,
    "stops": 1
  },
  {
    "id": 80,
    "flightNumber": "AI646",
    "airline": "Air India",
    "from": "Pune",
    "to": "Bangalore",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "03:26",
    "arrivalTime": "05:41",
    "duration": "2h 15m",
    "travelClass": "Economy",
    "price": 8594,
    "stops": 1
  },
  {
    "id": 81,
    "flightNumber": "IN338",
    "airline": "IndiGo",
    "from": "Delhi",
    "to": "Kolkata",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "17:40",
    "arrivalTime": "21:10",
    "duration": "3h 30m",
    "travelClass": "Economy",
    "price": 5534,
    "stops": 0
  },
  {
    "id": 82,
    "flightNumber": "GO528",
    "airline": "Go First",
    "from": "Bangalore",
    "to": "Hyderabad",
    "departureDate": "2025-05-29",
    "returnDate": "",
    "departureTime": "18:18",
    "arrivalTime": "20:03",
    "duration": "1h 45m",
    "travelClass": "Economy",
    "price": 4740,
    "stops": 1
  },
  {
    "id": 83,
    "flightNumber": "SP347",
    "airline": "SpiceJet",
    "from": "Kolkata",
    "to": "Bangalore",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "23:57",
    "arrivalTime": "04:12",
    "duration": "4h 15m",
    "travelClass": "Economy",
    "price": 5208,
    "stops": 1
  },
  {
    "id": 84,
    "flightNumber": "IN173",
    "airline": "IndiGo",
    "from": "Bangalore",
    "to": "Chennai",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "20:56",
    "arrivalTime": "02:11",
    "duration": "5h 15m",
    "travelClass": "Economy",
    "price": 6054,
    "stops": 1
  },
  {
    "id": 85,
    "flightNumber": "IN402",
    "airline": "IndiGo",
    "from": "Chennai",
    "to": "Kolkata",
    "departureDate": "2025-05-22",
    "returnDate": "",
    "departureTime": "15:50",
    "arrivalTime": "18:05",
    "duration": "2h 15m",
    "travelClass": "Economy",
    "price": 9889,
    "stops": 0
  },
  {
    "id": 86,
    "flightNumber": "AI259",
    "airline": "Air India",
    "from": "Mumbai",
    "to": "Ahmedabad",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "01:51",
    "arrivalTime": "06:21",
    "duration": "4h 30m",
    "travelClass": "Economy",
    "price": 4322,
    "stops": 1
  },
  {
    "id": 87,
    "flightNumber": "IN696",
    "airline": "IndiGo",
    "from": "Bangalore",
    "to": "Mumbai",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "18:06",
    "arrivalTime": "20:06",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 4621,
    "stops": 1
  },
  {
    "id": 88,
    "flightNumber": "AI132",
    "airline": "Air India",
    "from": "Delhi",
    "to": "Ahmedabad",
    "departureDate": "2025-05-26",
    "returnDate": "",
    "departureTime": "16:00",
    "arrivalTime": "18:45",
    "duration": "2h 45m",
    "travelClass": "Economy",
    "price": 8174,
    "stops": 1
  },
  {
    "id": 89,
    "flightNumber": "AI194",
    "airline": "AirAsia",
    "from": "Pune",
    "to": "Hyderabad",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "02:29",
    "arrivalTime": "05:29",
    "duration": "3h",
    "travelClass": "Economy",
    "price": 4489,
    "stops": 0
  },
  {
    "id": 90,
    "flightNumber": "SP513",
    "airline": "SpiceJet",
    "from": "Ahmedabad",
    "to": "Bangalore",
    "departureDate": "2025-05-23",
    "returnDate": "",
    "departureTime": "21:05",
    "arrivalTime": "23:05",
    "duration": "2h",
    "travelClass": "Economy",
    "price": 4168,
    "stops": 1
  },
  {
    "id": 91,
    "flightNumber": "SP900",
    "airline": "SpiceJet",
    "from": "Hyderabad",
    "to": "Delhi",
    "departureDate": "2025-05-27",
    "returnDate": "",
    "departureTime": "16:56",
    "arrivalTime": "20:56",
    "duration": "4h",
    "travelClass": "Economy",
    "price": 5918,
    "stops": 1
  },
  {
    "id": 92,
    "flightNumber": "AI833",
    "airline": "AirAsia",
    "from": "Delhi",
    "to": "Ahmedabad",
    "departureDate": "2025-05-30",
    "returnDate": "",
    "departureTime": "13:57",
    "arrivalTime": "17:12",
    "duration": "3h 15m",
    "travelClass": "Economy",
    "price": 7334,
    "stops": 1
  },
  {
    "id": 93,
    "flightNumber": "GO618",
    "airline": "Go First",
    "from": "Kolkata",
    "to": "Mumbai",
    "departureDate": "2025-05-21",
    "returnDate": "",
    "departureTime": "22:27",
    "arrivalTime": "03:42",
    "duration": "5h 15m",
    "travelClass": "Economy",
    "price": 3856,
    "stops": 0
  },
  {
    "id": 94,
    "flightNumber": "AI120",
    "airline": "Air India",
    "from": "Bangalore",
    "to": "Kolkata",
    "departureDate": "2025-05-28",
    "returnDate": "",
    "departureTime": "16:12",
    "arrivalTime": "18:57",
    "duration": "2h 45m",
    "travelClass": "Economy",
    "price": 3742,
    "stops": 1
  },
  {
    "id": 95,
    "flightNumber": "GO730",
    "airline": "Go First",
    "from": "Ahmedabad",
    "to": "Kolkata",
    "departureDate": "2025-05-20",
    "returnDate": "",
    "departureTime": "18:24",
    "arrivalTime": "23:54",
    "duration": "5h 30m",
    "travelClass": "Economy",
    "price": 9370,
    "stops": 1
  }
    ];
  }

  toggleFilter(type: 'stops' | 'airlines', value: number | string) {
    const filterSet = this.filters[type] as Set<any>;
    if (filterSet.has(value)) {
      filterSet.delete(value);
    } else {
      filterSet.add(value);
    }
    this.applyFilters();
  }
 // Update the max price filter
  updatePrice(price: number) {
    this.filters.maxPrice = price;
    this.applyFilters();
  }

  // Apply all filters
  applyFilters() {
    this.filteredFlights = this.flights.filter(f =>
      f.price <= this.filters.maxPrice &&
      (this.filters.stops.size === 0 || this.filters.stops.has(f.stops)) &&
      (this.filters.airlines.size === 0 || this.filters.airlines.has(f.airline))
    );

    this.paginate();
  }

  // Pagination logic
  paginate() {
    const startIndex = (this.currentPage - 1) * this.flightsPerPage;
    const endIndex = startIndex + this.flightsPerPage;
    this.filteredFlights = this.filteredFlights.slice(startIndex, endIndex);
  }

  // Go to a specific page
  goToPage(page: number) {
    this.currentPage = page;
    this.paginate();
  }
}

